repos:
  # 1️⃣ Limpeza e verificação básica do Git
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: mkdocs.yml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=3000']

  # 2️⃣ Formatação de código
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: [--line-length=88]

  # 3️⃣ Linter moderno unificado
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff
        args: ["--select=E,F,W,C,D,I"]  # Customize conforme seu estilo
        additional_dependencies: []

  # 4️⃣ Tipagem estática
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args: ["--strict", "--show-error-codes", "src/"]
        language: system

  # 5️⃣ Segurança
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: [--recursive, --exclude=tests/, --skip=B101]

  # 6️⃣ Validação de mensagens de commit
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.18.0
    hooks:
      - id: gitlint
        stages: [commit-msg]

fail_fast: false
default_stages: [pre-commit]
